sun4i-drm-y += sun4i_backend.o
sun4i-drm-y += sun4i_crtc.o
sun4i-drm-y += sun4i_drv.o
sun4i-drm-y += sun4i_framebuffer.o
sun4i-drm-y += sun4i_layer.o
sun4i-drm-y += sun4i_tcon.o

sun4i-drm-y += sun4i_rgb.o
sun4i-drm-y += sun4i_tv.o

obj-$(CONFIG_DRM_SUN4I)		+= sun4i-drm.o
